import { JobOffer, JobSource } from '../types';

export const mockJobOffers: JobOffer[] = [
  {
    id: '1',
    title: 'Senior Full Stack Developer',
    company: 'TechCorp Inc.',
    location: 'San Francisco, CA (Remote)',
    type: 'Full-time',
    salary: '$140k - $180k',
    description: 'We are looking for an experienced Full Stack Developer to join our growing team. You will work on cutting-edge projects using modern technologies.',
    requirements: [
      '5+ years of experience in web development',
      'Strong proficiency in React and Node.js',
      'Experience with TypeScript',
      'Knowledge of cloud platforms (AWS/GCP)',
    ],
    stack: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS'],
    experience: 'Senior',
    postedDate: '2025-10-15',
    source: 'LinkedIn Jobs',
    url: 'https://example.com/job/1',
    isMatch: true,
    matchScore: 95,
    aiSummary: 'Excellent match! This role aligns perfectly with your React and Node.js expertise. The company offers competitive compensation and remote flexibility.',
  },
  {
    id: '2',
    title: 'Frontend Engineer',
    company: 'StartupXYZ',
    location: 'New York, NY',
    type: 'Full-time',
    salary: '$120k - $150k',
    description: 'Join our dynamic team building the next generation of web applications. We value creativity and innovation.',
    requirements: [
      '3+ years of React experience',
      'Strong CSS and UI/UX skills',
      'Experience with state management (Redux/Zustand)',
      'Portfolio of previous work',
    ],
    stack: ['React', 'Redux', 'CSS', 'JavaScript', 'Figma'],
    experience: 'Mid-level',
    postedDate: '2025-10-14',
    source: 'Indeed',
    url: 'https://example.com/job/2',
    isMatch: true,
    matchScore: 88,
    aiSummary: 'Strong match! Your React skills are a perfect fit. The role emphasizes UI/UX which matches your design background.',
  },
  {
    id: '3',
    title: 'Backend Developer - Python',
    company: 'DataDriven Co.',
    location: 'Austin, TX (Hybrid)',
    type: 'Full-time',
    salary: '$130k - $160k',
    description: 'Looking for a Python expert to work on our data processing pipelines and API development.',
    requirements: [
      '4+ years Python experience',
      'Experience with Django or Flask',
      'Knowledge of database optimization',
      'Understanding of microservices architecture',
    ],
    stack: ['Python', 'Django', 'PostgreSQL', 'Redis', 'Docker'],
    experience: 'Senior',
    postedDate: '2025-10-13',
    source: 'GitHub Jobs',
    url: 'https://example.com/job/3',
    isMatch: false,
    matchScore: 45,
    aiSummary: 'Partial match. While the role is senior-level, your primary stack is JavaScript/TypeScript rather than Python.',
  },
  {
    id: '4',
    title: 'React Native Developer',
    company: 'MobileFirst',
    location: 'Remote',
    type: 'Contract',
    salary: '$80 - $100/hr',
    description: 'We need an experienced React Native developer for a 6-month project building a cross-platform mobile app.',
    requirements: [
      '3+ years React Native experience',
      'Published apps on App Store and Play Store',
      'Experience with native modules',
      'Strong debugging skills',
    ],
    stack: ['React Native', 'TypeScript', 'Redux', 'Firebase'],
    experience: 'Mid-level',
    postedDate: '2025-10-16',
    source: 'We Work Remotely',
    url: 'https://example.com/job/4',
    isMatch: true,
    matchScore: 82,
    aiSummary: 'Good match! Your React experience translates well to React Native. The remote and contract nature offers flexibility.',
  },
  {
    id: '5',
    title: 'Junior Web Developer',
    company: 'Agency Pro',
    location: 'Los Angeles, CA',
    type: 'Full-time',
    salary: '$65k - $85k',
    description: 'Entry-level position for a motivated developer to work on client projects. Great learning opportunity.',
    requirements: [
      '1+ year of web development experience',
      'Basic HTML, CSS, JavaScript knowledge',
      'Eager to learn and grow',
      'Good communication skills',
    ],
    stack: ['HTML', 'CSS', 'JavaScript', 'WordPress', 'jQuery'],
    experience: 'Junior',
    postedDate: '2025-10-12',
    source: 'AngelList',
    url: 'https://example.com/job/5',
    isMatch: false,
    matchScore: 30,
    aiSummary: 'Below your experience level. This junior role may not challenge your senior-level skills.',
  },
  {
    id: '6',
    title: 'Full Stack Engineer - Next.js',
    company: 'Modern Web Co.',
    location: 'Remote (US Only)',
    type: 'Full-time',
    salary: '$150k - $190k',
    description: 'Build scalable web applications using Next.js and modern web technologies. Join a team of passionate engineers.',
    requirements: [
      '4+ years full stack experience',
      'Expert-level Next.js knowledge',
      'Experience with serverless architecture',
      'Strong TypeScript skills',
    ],
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind', 'Vercel', 'Supabase'],
    experience: 'Senior',
    postedDate: '2025-10-17',
    source: 'Hacker News',
    url: 'https://example.com/job/6',
    isMatch: true,
    matchScore: 98,
    aiSummary: 'Outstanding match! This role perfectly aligns with your Next.js and React expertise. Top-tier compensation and fully remote.',
  },
];

export const mockJobSources: JobSource[] = [
  {
    id: '1',
    name: 'LinkedIn Jobs RSS',
    type: 'RSS',
    url: 'https://www.linkedin.com/jobs/rss',
    enabled: true,
    lastSync: '2025-10-17T10:30:00Z',
  },
  {
    id: '2',
    name: 'Indeed API',
    type: 'API',
    url: 'https://api.indeed.com/jobs',
    enabled: true,
    lastSync: '2025-10-17T09:15:00Z',
  },
  {
    id: '3',
    name: 'GitHub Jobs Feed',
    type: 'RSS',
    url: 'https://jobs.github.com/positions.json',
    enabled: true,
    lastSync: '2025-10-17T08:00:00Z',
  },
  {
    id: '4',
    name: 'Email Alerts (jobs@inbox)',
    type: 'Email',
    url: 'jobs@youremail.com',
    enabled: false,
    lastSync: undefined,
  },
  {
    id: '5',
    name: 'Stack Overflow Jobs',
    type: 'RSS',
    url: 'https://stackoverflow.com/jobs/feed',
    enabled: true,
    lastSync: '2025-10-16T22:45:00Z',
  },
];
